### ISSUE TITLE
Need of a "nil" body to close a tag

### ISSUE THREAD

**Issue by vindarel** [arielnetworks/cl-markup#11]
Hi,

edit: I was traped by something not identified in this message.

it wasn't obvious to me that tags are not closed if they have no body:

    (markup (:br))
    ;=> "<br />"

whereas

    (markup (:br nil))
    ;=> "<br></br>"

This can be an issue for html generation and is surely a trap easy to fall into.

It doesn't help to set the style:

    (eval-when (:compile-toplevel :load-toplevel :execute)
      (setf *markup-language* :html))
    (markup (:p))
    ;; => "<p>" (and nothing closing)

So am I doing sthg wrong and is it possible to have auto-closing tags with no body ?

**Comment by erjoalgo** [comment]
It would be helpful if this was included as part of the README. Some html tags e.g. `textarea`, seem to require explict closing tags.
