### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by eudoxia0** [arielnetworks/cl-markup#8]
I've been testing the performance of different Common Lisp template libraries (And some of other languages) and have run into a pretty surprising result: cl-markup is significantly slower than Jinja2, and other templating engines.

The test is simple: A ten-thousand-element list is render in `<li>` tags and a similarly large hash table is rendered as a definition list.

The Jinja2 code is:

``` python
from datetime import datetime
from jinja2 import Template

TEMPLATE = '''
List:
<ol>
  {% for item in list %}
    <li>{{item}}</li>
  {% endfor %}
</ol>
Dictionary:
<dl>
  {% for key, value in dict.iteritems() %}
    <dt>{{key}}</dt>
    <dd>{{value}}</dd>
  {% endfor %}
</dl>
'''

LIST = [i for i in xrange(1,10000)]
DICT = {i:i*2 for i in LIST}

if __name__ == '__main__':
    template = Template(TEMPLATE)
    start = datetime.now()
    template.render(list=LIST, dict=DICT)
    end = datetime.now()
    print "Jinja2:", (end-start).microseconds/1e6
```

The cl-markup code is:

``` lisp
(ql:quickload :cl-markup)

(defparameter +list+ (loop for i from 0 to 10000 collecting i))
(defparameter +dict+ (let ((table (make-hash-table)))
                       (loop for item in +list+ do
                         (setf (gethash item table) item))
                       table))

(declaim (optimize (speed 3) (debug 0)))

(setf markup:*output-stream* nil)

(defun template ()
  (markup:markup
   (:ol
    (loop for item in +list+ do
      (markup:markup (:li item))))
   (:dl
    (loop for key being the hash-keys of +dict+
          for value being the hash-values of +dict+
          do
             (markup:markup (:dt key)
                            (:dd value))))))

(let ((start (get-internal-real-time)))
  (template)
  (format t "cl-markup: ~6$~&"
          (/ (- (get-internal-real-time) start)
             internal-time-units-per-second)))
```

I ran all the tests in a 64-bit Ubuntu Precise virtual machine with 2048 MB of RAM and two CPUs, on SBCL 1.0.55.0.debian. The results are pretty strange:

```
vagrant@precise64:~$ bash benchmark.sh 
Jinja2: 0.028667s
cl-markup: 0.247000s
```

Thoughts? Anything obvious I am doing wrong?

EDIT: Calling `(compile 'template)` brought it down to, 0.148000s, but it's still too high.

EDIT: After testing cl-who, it does the work in 0.027s, on par with Jinja but far slower than cl-markup.

**Comment by epipping** [comment]
> After testing cl-who, it does the work in 0.027s, on par with Jinja but far slower than cl-markup

Unless I misunderstand, you meant to say:

> After testing cl-who, it does the work in 0.027s, on par with Jinja and far faster than cl-markup

right?

**Comment by eudoxia0** [comment]
Yes. I actually noticed that error a while back but didn't bother to correct it since it's a two-year-old report and I've moved on to Djula now.
